use bdColegio;
/*---------------------------------------ESTUDIANTE Nº1---------------------------------------------------------*//*
call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106602, "Primer Periodo", 3.0, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106602, "Primer Periodo", 3.2, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106602, "Primer Periodo", 2.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106602, "Primer Periodo", 2.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106602, "Primer Periodo", 3.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106602, "Primer Periodo", 3.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106602, "Primer Periodo", 3.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106602, "Segundo Periodo", 3.3, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106602, "Segundo Periodo", 3.4, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106602, "Segundo Periodo", 2.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106602, "Segundo Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106602, "Segundo Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106602, "Segundo Periodo", 3.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Segundo Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106602, "Segundo Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106602, "Segundo Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Segundo Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106602, "Segundo Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106602, "Segundo Periodo", 4.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106602, "Segundo Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106602, "Segundo Periodo", 4.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106602, "Segundo Periodo", 3.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106602, "Tercer Periodo", 3.5, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106602, "Tercer Periodo", 3.6, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106602, "Tercer Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106602, "Tercer Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106602, "Tercer Periodo", 2.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106602, "Tercer Periodo", 2.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Tercer Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106602, "Tercer Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106602, "Tercer Periodo", 2.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Tercer Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106602, "Tercer Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106602, "Tercer Periodo", 4.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106602, "Tercer Periodo", 4.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106602, "Tercer Periodo", 4.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106602, "Tercer Periodo", 4.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106602, "Cuarto Periodo", 4.5, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106602, "Cuarto Periodo", 2.6, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106602, "Cuarto Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106602, "Cuarto Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106602, "Cuarto Periodo", 4.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106602, "Cuarto Periodo", 4.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Cuarto Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106602, "Cuarto Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106602, "Cuarto Periodo", 4.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106602, "Cuarto Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106602, "Cuarto Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106602, "Cuarto Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106602, "Cuarto Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106602, "Cuarto Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106602, "Cuarto Periodo", 3.8, 1);

/*---------------------------------------ESTUDIANTE Nº2---------------------------------------------------------*//*
call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106840, "Primer Periodo", 3.1, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106840, "Primer Periodo", 3.3, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106840, "Primer Periodo", 2.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106840, "Primer Periodo", 2.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106840, "Primer Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106840, "Primer Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Primer Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106840, "Primer Periodo", 3.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106840, "Primer Periodo", 3.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Primer Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106840, "Primer Periodo", 3.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106840, "Primer Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106840, "Primer Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106840, "Primer Periodo", 3.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106840, "Primer Periodo", 3.4, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106840, "Segundo Periodo", 3.7, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106840, "Segundo Periodo", 3.4, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106840, "Segundo Periodo", 2.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106840, "Segundo Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106840, "Segundo Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106840, "Segundo Periodo", 3.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Segundo Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106840, "Segundo Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106840, "Segundo Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Segundo Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106840, "Segundo Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106840, "Segundo Periodo", 4.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106840, "Segundo Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106840, "Segundo Periodo", 4.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106840, "Segundo Periodo", 3.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106840, "Tercer Periodo", 3.5, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106840, "Tercer Periodo", 3.6, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106840, "Tercer Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106840, "Tercer Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106840, "Tercer Periodo", 2.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106840, "Tercer Periodo", 2.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Tercer Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106840, "Tercer Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106840, "Tercer Periodo", 2.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Tercer Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106840, "Tercer Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106840, "Tercer Periodo", 4.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106840, "Tercer Periodo", 4.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106840, "Tercer Periodo", 4.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106840, "Tercer Periodo", 4.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106840, "Cuarto Periodo", 4.5, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106840, "Cuarto Periodo", 2.6, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106840, "Cuarto Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106840, "Cuarto Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106840, "Cuarto Periodo", 4.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106840, "Cuarto Periodo", 4.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Cuarto Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106840, "Cuarto Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106840, "Cuarto Periodo", 4.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106840, "Cuarto Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106840, "Cuarto Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106840, "Cuarto Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106840, "Cuarto Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106840, "Cuarto Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106840, "Cuarto Periodo", 3.8, 1);*/

/*---------------------------------------ESTUDIANTE Nº3---------------------------------------------------------*/
call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106621, "Primer Periodo", 3.1, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106621, "Primer Periodo", 3.3, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106621, "Primer Periodo", 2.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106621, "Primer Periodo", 2.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106621, "Primer Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106621, "Primer Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Primer Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106621, "Primer Periodo", 3.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106621, "Primer Periodo", 3.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Primer Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106621, "Primer Periodo", 3.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106621, "Primer Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106621, "Primer Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106621, "Primer Periodo", 3.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106621, "Primer Periodo", 3.4, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106621, "Segundo Periodo", 3.7, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106621, "Segundo Periodo", 3.4, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106621, "Segundo Periodo", 2.5, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106621, "Segundo Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106621, "Segundo Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106621, "Segundo Periodo", 3.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Segundo Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106621, "Segundo Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106621, "Segundo Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Segundo Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106621, "Segundo Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106621, "Segundo Periodo", 4.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106621, "Segundo Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106621, "Segundo Periodo", 4.3, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106621, "Segundo Periodo", 3.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106621, "Tercer Periodo", 3.5, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106621, "Tercer Periodo", 3.6, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106621, "Tercer Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106621, "Tercer Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106621, "Tercer Periodo", 2.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106621, "Tercer Periodo", 2.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Tercer Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106621, "Tercer Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106621, "Tercer Periodo", 2.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Tercer Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106621, "Tercer Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106621, "Tercer Periodo", 4.0, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106621, "Tercer Periodo", 4.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106621, "Tercer Periodo", 4.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106621, "Tercer Periodo", 4.0, 1);

call registrarDocenteNotasAsistenciasPeriodo("Matemáticas", 106621, "Cuarto Periodo", 4.5, 8);
call registrarDocenteNotasAsistenciasPeriodo("Informática", 106621, "Cuarto Periodo", 2.6, 6);
call registrarDocenteNotasAsistenciasPeriodo("Convivencia", 106621, "Cuarto Periodo", 3.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Español", 106621, "Cuarto Periodo", 2.8, 1);
call registrarDocenteNotasAsistenciasPeriodo("Inglés", 106621, "Cuarto Periodo", 4.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias Naturales", 106621, "Cuarto Periodo", 4.6, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Cuarto Periodo", 3.9, 1);
call registrarDocenteNotasAsistenciasPeriodo("Religión", 106621, "Cuarto Periodo", 3.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ética y valores", 106621, "Cuarto Periodo", 4.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ciencias sociales", 106621, "Cuarto Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Edu. Física", 106621, "Cuarto Periodo", 3.7, 1);
call registrarDocenteNotasAsistenciasPeriodo("Proyecto Pedagógico Productivo", 106621, "Cuarto Periodo", 4.1, 1);
call registrarDocenteNotasAsistenciasPeriodo("Ecología", 106621, "Cuarto Periodo", 3.2, 1);
call registrarDocenteNotasAsistenciasPeriodo("Artística", 106621, "Cuarto Periodo", 3.4, 1);
call registrarDocenteNotasAsistenciasPeriodo("Emprendimiento", 106621, "Cuarto Periodo", 3.8, 1);


